# Generated by Django 6.0 on 2026-01-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_predictionsguest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionsGuest',
        ),
    ]
