"""creating players table

Revision ID: 14fd667c55d8
Revises: 2cc39889c908
Create Date: 2026-01-31 17:16:46.264851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fd667c55d8'
down_revision: Union[str, Sequence[str], None] = '2cc39889c908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
